### ISSUE TITLE
[1.2.2] Slider déphaser entre desktop et App Mobile

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues-app#11]
Sur l'app mobile, les lumières avec sliders apparaissent à 0% alors qu'elles sont bien allumées.
Sur le dash, la valeur du slider remonte bien comme il faut.

![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/11528172/31615742-de4f76a8-b28a-11e7-8003-a1162e7e3747.png)
<img width="512" alt="capture_d___cran_2017-10-09_08 19 33_1024" src="https://user-images.githubusercontent.com/11528172/31615744-deb25aca-b28a-11e7-924f-aed344eca5bb.png">

**Comment by rocket13011** [comment]
https://jeedom.atlassian.net/browse/JEED-41
