### ISSUE TITLE
[1.2.2] plugin alarme 

### ISSUE THREAD

**Issue by Babatou** [jeedom/issues-app#12]
Si on ajoute le plugin alarme dans l'application Android (sur le deuxième écran)
Lorsque l'on click dessus par la suite on a de nouveau l'écran pour choisir ce que l'on souhaite ajouter au bouton (comme si on clique sur un + à coté)
Si on fait retour alors le plugin s'affiche.

**Comment by rocket13011** [comment]
problème detecter sur Android et iOS.
résolution en cours

**Comment by rocket13011** [comment]
https://jeedom.atlassian.net/browse/JEED-40
