### ISSUE TITLE
[Thermostat-Agenda] Smart Start

### ISSUE THREAD

**Issue by Babatou** [jeedom/issues-app#18]
Si l'agenda à l'origine de la programmation d'un Smart start est désactivé après l'écriture de l'entrée cron par le plugin thermostat, le chauffage démarre quand même car thermostat ne vérifie pas dans sa fonction pull() si l'agenda est toujours actif. 
Comme seulement la première entrée est observée car pas remise à jour une fois l'agenda désactivé, les autres actions programmées (changement de consigne, arrêt) ne sont pas lancées.

**Comment by rocket13011** [comment]
A mettre dans Jira (Prochainement) pour le plugin Thermostat
