### ISSUE TITLE
[core]les issues du core on disparues

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues-app#19]
Le message de issue-app revoyant une erreur 404.
https://github.com/jeedom/issues

**Comment by spyjo** [comment]
+1 on fait comment pour en soumettre dorénavant ?

**Comment by rocket13011** [comment]
vous passez par la rubrique bug sur le market ou sur votre Jeedom (comme pour un ticket).
Attention c'est uniquement pour les bug
