### ISSUE TITLE
Création de nouveaux Types Génériques

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues-app#8]
Un info/LIGHT_COLOR_TEMP et un action/LIGHT_SET_COLOR_TEMP qui est un slider (0-255 ou 2200-4000 ou 1700-6500)
Pour gérer les couleurs de températures

Un info/LIGHT_STATE_BOOL qui sera sur l'état booleen, s'il est présent, c'est cet état qui déterminera le ON/OFF, sinon c'est la luminosité à 0 ou !=

Un info/ACTIVE qui sera un booléen à appliquer à un status ONLINE d'une lumière mais peut-etre utilisé pour un autre élément éventuellement.

**Comment by rocket13011** [comment]
Fait manquera ACTIVE
